### ISSUE TITLE
Question: where is the example?

### ISSUE THREAD

**Issue by vanesca88** [pmndrs/cannon-es-debugger#15]
Truly wonderful library (Cannon-es)
But I'm having a hard time seeing how to implement the debugger version.
Is there an example html file anywhere, that I can run?

**Comment by vanesca88** [comment]
Anyone?

**Comment by vanesca88** [comment]
Pretty rude to just close it. Was a completely normal question.
Only been waiting for 2 months.

**Comment by stockHuman** [comment]
Hi @vanesca88, _issues_ are for reporting bugs or missing features, which in fairness to you - documentation certainly is such a thing. However, instructions on how to get the debugger running in your scene are the first thing in the readme:

```js
import { Scene } from 'three'
import { World } from 'cannon-es'
import cannonDebugger from 'cannon-es-debugger'

const scene = new Scene()
const world = new World()
cannonDebugger(scene, world.bodies, options)
```

We have a [discord](https://pmnd.rs/discord) running that works like a help forum for the whole ecosystem, albeit you'll find debugger questions under #cannon-es.

If there's an problem with the above snippet (it doesn't work for whatever reason), please describe that issue. Else, I'm sorry, but no one was going to answer this because it's well outside of the scope of this library as phrased. For your reference: [a CSB with the debugger lines commented out](https://codesandbox.io/s/pushy-words-32kiv?file=/src/index.js).

**Comment by marcofugaro** [comment]
Hey I had converted the example file locally, but didn't manage to push it.

Reooening this as a reminder.

**Comment by krispya** [comment]
> Hey I had converted the example file locally, but didn't manage to push it.
> 
> Reopening this as a reminder.

To test some changes, I started making an example but then I saw you had one. Is it something you can still push?
